name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  dist_sh_develop:
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - "5.40"

    runs-on: ubuntu-latest

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use cache
        uses: actions/cache@v4
        with:
          path: local/
          key: cpm-ci-dist-sh-develop-${{ matrix.perl-version }}-${{ runner.os }}-${{ hashFiles('cpanfile') }}

      - name: Use local Perl packages
        run: |
          echo "$GITHUB_WORKSPACE/local/bin" | tee -a $GITHUB_PATH
          echo "PERL5LIB=$GITHUB_WORKSPACE/local/lib/perl5" | tee -a $GITHUB_ENV

      - name: Install cpm
        run: curl -fsSL https://raw.githubusercontent.com/skaji/cpm/main/cpm | perl - install --color --no-test App::cpm

      - name: Install required dependencies
        run: cpm install --color --no-test --with-configure --with-recommends --with-suggests

      - name: Install develop dependencies
        run: cpm install --color --no-test --with-develop

      - name: Make distribution
        run: ./Dist.SH
        env:
          GEOCODEFARM_API_KEY: ${{ secrets.GEOCODEFARM_API_KEY }}

  dist_sh:
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - "5.38"
          - "5.36"
          - "5.34"
          - "5.32"
          - "5.30"
          - "5.28"
          - "5.26"

    runs-on: ubuntu-latest

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use cache
        uses: actions/cache@v4
        with:
          path: local/
          key: cpm-ci-dist-sh-${{ matrix.perl-version }}-${{ runner.os }}-${{ hashFiles('cpanfile') }}

      - name: Use local Perl packages
        run: |
          echo "$GITHUB_WORKSPACE/local/bin" | tee -a $GITHUB_PATH
          echo "PERL5LIB=$GITHUB_WORKSPACE/local/lib/perl5" | tee -a $GITHUB_ENV

      - name: Install cpm
        run: curl -fsSL https://raw.githubusercontent.com/skaji/cpm/main/cpm | perl - install --color --no-test App::cpm

      - name: Install required dependencies
        run: cpm install --color --no-test --with-configure --with-recommends --with-suggests

      - name: Make distribution
        run: ./Dist.SH
        env:
          TEST_SKIP_DEVELOP: "1"
